<?php

namespace NG\AdministrateurBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{

    public function allEnts()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('e')
            ->from('NGAdministrateurBundle:Entreprise', 'e')
            ->orderBy('e.nom');
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
