<?php

namespace NG\AdministrateurBundle\Repository;

/**
 * TypeLotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLotRepository extends \Doctrine\ORM\EntityRepository
{
}
