<?php

namespace NG\AdministrateurBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{

    public function allUtilisateur()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('u')
            ->from('NGAdministrateurBundle:Utilisateur', 'u')
            ->orderBy('u.nom');
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }

}
