ng_gestionnaire_geolocalisation-region-index:
    path:     /ng/geolocalisation/region
    defaults: { _controller: NGGestionnaireBundle:Region:index }

ng_gestionnaire_geolocalisation-region-add:
    path:     /ng/geolocalisation/region/ajout
    defaults: { _controller: NGGestionnaireBundle:Region:add }

ng_gestionnaire_geolocalisation-dept-index:
    path:     /ng/geolocalisation/departement
    defaults: { _controller: NGGestionnaireBundle:Departement:index }

ng_gestionnaire_geolocalisation-dept-add:
    path:     /ng/geolocalisation/departement/ajout
    defaults: { _controller: NGGestionnaireBundle:Departement:add }

ng_gestionnaire_geolocalisation-ville-index:
    path:     /ng/geolocalisation/ville
    defaults: { _controller: NGGestionnaireBundle:Ville:index }

ng_gestionnaire_geolocalisation-ville-add:
    path:     /ng/geolocalisation/ville/ajout
    defaults: { _controller: NGGestionnaireBundle:Ville:add }

ng_gestionnaire_geolocalisation-carte:
    path:     /ng/geolocalisation/carte
    defaults: { _controller: NGGestionnaireBundle:Immeuble:map }

ng_gestionnaire_immeuble-index:
    path:     /ng/gestion/immeuble
    defaults: { _controller: NGGestionnaireBundle:Immeuble:index }

ng_gestionnaire_immeuble-add:
    path:     /ng/gestion/immeuble/ajout
    defaults: { _controller: NGGestionnaireBundle:Immeuble:add }

ng_gestionnaire_proprietaire-index:
    path:     /ng/gestion/proprietaire
    defaults: { _controller: NGGestionnaireBundle:Proprietaire:index }

ng_gestionnaire_proprietaire-add:
    path:     /ng/gestion/proprietaire/ajout
    defaults: { _controller: NGGestionnaireBundle:Proprietaire:add }

ng_gestionnaire_proprietaire-pdf:
    path:     /ng/gestion/proprietaire/pdf/{id}
    defaults: { _controller: NGGestionnaireBundle:Proprietaire:pdf }

ng_gestionnaire_proprietaire-consult:
    path:     /ng/gestion/proprietaire/{id}
    defaults: { _controller: NGGestionnaireBundle:Proprietaire:consult }

ng_gestionnaire_immeuble:
    path:     /ng/gestion/immeuble/code/{code}
    defaults: { _controller: NGGestionnaireBundle:Immeuble:uneCopro }

ng_gestionnaire_immeuble-lot-add:
    path:     /ng/gestion/immeuble/ajout/lot/{code}
    defaults: { _controller: NGGestionnaireBundle:Lot:add }

ng_gestionnaire_immeuble-lot-pdf:
    path:     /ng/gestion/immeuble/pdf/lot/{id}
    defaults: { _controller: NGGestionnaireBundle:Lot:pdf }

ng_gestionnaire_immeuble-lot-prop-add:
    path:     /ng/gestion/immeuble/ajout/lot/proprietaire/{code}
    defaults: { _controller: NGGestionnaireBundle:Proprietaire:prop_lotAdd }

ng_gestionnaire_immeuble-habitant-add:
    path:     /ng/gestion/immeuble/ajout/habitant/{code}
    defaults: { _controller: NGGestionnaireBundle:Habitant:add }

ng_gestionnaire_immeuble-habitant-pdf:
    path:     /ng/gestion/immeuble/pdf/habitant/{id}
    defaults: { _controller: NGGestionnaireBundle:Habitant:pdf }

ng_gestionnaire_immeuble-ag-add:
    path:     /ng/gestion/immeuble/ajout/ag/{code}
    defaults: { _controller: NGGestionnaireBundle:AG:add }

ng_gestionnaire_immeuble-cs-add:
    path:     /ng/gestion/immeuble/ajout/cs/{code}
    defaults: { _controller: NGGestionnaireBundle:CS:add }

ng_gestionnaire_immeuble-sinistre-add:
    path:     /ng/gestion/immeuble/ajout/sinistre/{code}
    defaults: { _controller: NGGestionnaireBundle:Sinistre:add }

ng_gestionnaire_sinistre-index:
    path:     /ng/gestion/sinistre/{code}
    defaults: { _controller: NGGestionnaireBundle:Sinistre:index }

ng_gestionnaire_sinistre-liste:
    path:     /ng/gestion/sinistre
    defaults: { _controller: NGGestionnaireBundle:Sinistre:liste }

ng_gestionnaire_sinistre-pdf:
    path:     /ng/gestion/immeuble/pdf/sinistre/{id}
    defaults: { _controller: NGGestionnaireBundle:Sinistre:pdf }
