<?php

namespace Proxies\__CG__\NG\GestionnaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lot extends \NG\GestionnaireBundle\Entity\Lot implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'id', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'num', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'etage', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'surface', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'carezze', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'prix', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'proprietaire', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'copro', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'typeLot'];
        }

        return ['__isInitialized__', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'id', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'num', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'etage', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'surface', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'carezze', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'prix', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'proprietaire', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'copro', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\Lot' . "\0" . 'typeLot'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lot $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNum($num)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNum', [$num]);

        return parent::setNum($num);
    }

    /**
     * {@inheritDoc}
     */
    public function getNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNum', []);

        return parent::getNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtage($etage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtage', [$etage]);

        return parent::setEtage($etage);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtage', []);

        return parent::getEtage();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface($surface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', [$surface]);

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', []);

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarezze($carezze)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarezze', [$carezze]);

        return parent::setCarezze($carezze);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarezze()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarezze', []);

        return parent::getCarezze();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setProprietaire(\NG\GestionnaireBundle\Entity\Proprietaire $proprietaire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProprietaire', [$proprietaire]);

        return parent::setProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeLot(\NG\AdministrateurBundle\Entity\TypeLot $typeLot = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeLot', [$typeLot]);

        return parent::setTypeLot($typeLot);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeLot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeLot', []);

        return parent::getTypeLot();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopro(\NG\GestionnaireBundle\Entity\Copropriete $copro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopro', [$copro]);

        return parent::setCopro($copro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopro', []);

        return parent::getCopro();
    }

}
