<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * CoproprieteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoproprieteRepository extends \Doctrine\ORM\EntityRepository
{

    public function allCopro()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('NGGestionnaireBundle:Copropriete', 'c')
            ->orderBy('c.code');
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

    public function uneCopro($code)
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('NGGestionnaireBundle:Copropriete', 'c')
            ->where('c.code = :code')
            ->setParameter('code', $code);
        $query = $qb->getQuery();
        $resultat = $query->getOneOrNullResult();
        return $resultat;
    }

}
