<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * CSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CSRepository extends \Doctrine\ORM\EntityRepository
{

    public function lesCS($copro)
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('c')
            ->from('NGGestionnaireBundle:CS', 'c')
            ->where('c.copro = :copro')
            ->setParameter('copro', $copro);
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }


}
