<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * ImageSinistreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSinistreRepository extends \Doctrine\ORM\EntityRepository
{

    public function lesImgs($code)
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('i')
            ->from('NGGestionnaireBundle:ImageSinistre', 'i')
            ->where('i.sinistre = :code')
            ->setParameter('code', $code);
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
