<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * ProprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireRepository extends \Doctrine\ORM\EntityRepository
{

    public function allProp()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('p')
            ->from('NGGestionnaireBundle:Proprietaire', 'p')
            ->orderBy('p.nom');
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
