<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{

    public function allRegion()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('r')
            ->from('NGGestionnaireBundle:Region', 'r')
            ->orderBy('r.nom');
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
