<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * SinEntRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinEntRepository extends \Doctrine\ORM\EntityRepository
{

    public function lesCouts($sin)
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('NGGestionnaireBundle:SinEnt', 's')
            ->where('s.sinistre = :sin')
            ->setParameter('sin', $sin);
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
