<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * SinistreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinistreRepository extends \Doctrine\ORM\EntityRepository
{

    public function lesSin($code)
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('NGGestionnaireBundle:Sinistre', 's')
            ->innerJoin('NGGestionnaireBundle:Lot', 'l')
            ->where('s.lot = l.id')
            ->andWhere('l.copro = :code')
            ->setParameter('code', $code);
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
