<?php

namespace NG\GestionnaireBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{

    public function allVille()
    {
        $qb =$this->_em->createQueryBuilder();
        $qb->select('v')
            ->from('NGGestionnaireBundle:Ville', 'v')
            ->orderBy('v.nom');
        $query = $qb->getQuery();
        $resultat = $query->getResult();
        return $resultat;
    }

}
