<?php

namespace Proxies\__CG__\NG\GestionnaireBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AG extends \NG\GestionnaireBundle\Entity\AG implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'id', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'ref', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'nbDecision', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'date', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'pdf', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'habitants', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'copro'];
        }

        return ['__isInitialized__', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'id', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'ref', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'nbDecision', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'date', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'pdf', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'habitants', '' . "\0" . 'NG\\GestionnaireBundle\\Entity\\AG' . "\0" . 'copro'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AG $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRef($ref)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRef', [$ref]);

        return parent::setRef($ref);
    }

    /**
     * {@inheritDoc}
     */
    public function getRef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', []);

        return parent::getRef();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbDecision($nbDecision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbDecision', [$nbDecision]);

        return parent::setNbDecision($nbDecision);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbDecision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbDecision', []);

        return parent::getNbDecision();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdf($pdf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdf', [$pdf]);

        return parent::setPdf($pdf);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdf', []);

        return parent::getPdf();
    }

    /**
     * {@inheritDoc}
     */
    public function addHabitant(\NG\GestionnaireBundle\Entity\Habitant $habitant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHabitant', [$habitant]);

        return parent::addHabitant($habitant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHabitant(\NG\GestionnaireBundle\Entity\Habitant $habitant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHabitant', [$habitant]);

        return parent::removeHabitant($habitant);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitants', []);

        return parent::getHabitants();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopro(\NG\GestionnaireBundle\Entity\Copropriete $copro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopro', [$copro]);

        return parent::setCopro($copro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopro', []);

        return parent::getCopro();
    }

}
